motivations = [
    "Stay Consistent",
    "Keep Moving Forward",
    "Discipline Activated",
    "One Step at a Time",
    "UNSWow Mode: ON",
    "Crush Your Goals",
    "Eyes on Caltech 👀",
    "Daily Grind 💪",
    "No Zero Days",
    "Win the Morning",
    "Built Not Born",
    "Push Your Limits",
    "Small Wins Matter",
    "Be Your Own Hero",
    "Focus. Fight. Finish.",
    "Sleep is Fuel",
    "Mindset is Everything",
    "Create, Don’t Consume",
    "Trust the Process",
    "Progress Over Perfection",
    "Sacrifice Now, Shine Later",
    "Embrace the Suck",
    "Systems > Willpower",
    "Consistency is King",
    "Clarity. Consistency. Caltech.",
    "Grind Now, Glory Later",
    "Action Beats Anxiety",
    "Sharp Mind, Strong Will",
    "Self-Discipline is Freedom",
    "Routine = Power",
    "Dream. Plan. Do.",
    "You Are What You Repeat",
    "Built Different",
    "Earned, Not Given",
    "Less Talk, More Code",
    "Outwork Yesterday",
    "Run Your Own Race",
    "Grit in Motion",
    "Unleash Your Focus",
    "No Excuses, Just Effort",
    "Get 1% Better Today",
    "Show Up Anyway",
    "Hard Choices, Easy Life",
    "Keep It Moving",
    "Self-Control = Superpower",
    "Read. Write. Refactor.",
    "Level Up Daily",
    "Build The Future",
    "Be Relentless",
    "Results Require Discipline",
    "Think Deep, Move Fast",
    "Keep It Hardcore",
    "Grind > Motivation",
    "Execution Over Excuses",
    "Hustle with Purpose",
    "Dominate the Day",
    "Code. Commit. Conquer.",
    "Fall Seven, Stand Eight",
    "Write Code, Rewrite Destiny",
    "Power Through",
    "Laser Focus Mode: ON",
    "UNSWow State: ACTIVE",
    "Discipline = Love for Future Self",
    "More Input, Less Dopamine",
    "Winners Build Habits",
    "Cut Distractions, Chase Goals",
    "Routine Beats Resistance",
    "Train the Mind Daily",
    "Hack Your Discipline",
    "Slow is Smooth, Smooth is Fast",
    "Mental Gym Every Day",
    "Calm but Unstoppable",
    "Sculpt Your Future",
    "Grind for the Greater Good",
    "Keep it Clean. Keep it Consistent.",
    "Brains + Biceps = UNSWow",
    "Don’t Break the Chain",
    "Build the System, Be the System",
    "Not Today, Procrastination.",
    "One Record Closer to Caltech",
    "Own Your Timeline",
    "Never Miss Twice"
    "UNSW — Leading innovation in education.",
    "Study smart, study at UNSW!",
    "Pushing boundaries, shaping the future — UNSW.",
    "Empowering minds, inspiring futures — UNSW.",
    "Excellence in education — UNSW!",
    "Innovate, lead, succeed — Join UNSW!",
    "UNSW — Shaping global leaders.",
    "A world of opportunities awaits at UNSW.",
    "Explore new horizons with UNSW.",
    "Proud to be a UNSW student!",
    "Engineering tomorrow’s breakthroughs at UNSW.",
    "UNSW — Where innovation meets excellence.",
    "Change the world with a degree from UNSW.",
    "Your future begins here — UNSW.",
    "UNSW — Building the leaders of tomorrow.",
    "Pioneering the future of technology at UNSW.",
    "From ideas to impact — UNSW at the forefront.",
    "Discover your potential with UNSW!",
    "UNSW — Shaping the future of education.",
    "Turning ambition into achievement — UNSW.",
    "The future is now at UNSW.",
    "Pushing the limits of knowledge at UNSW.",
    "Achieve your dreams with UNSW.",
    "UNSW — Empowering tomorrow's leaders.",
    "Excellence in every step — UNSW.",
    "UNSW — Where great minds come together.",
    "Unlock your future at UNSW.",
    "Explore endless possibilities at UNSW.",
    "Leading the way in higher education — UNSW.",
    "UNSW — Inspiring greatness in every student."
]

with open("motivations.txt", "w", encoding="utf-8") as f:
    for line in motivations:
        f.write(line + "\n")

print("motivations.txt 文件写入完成 ✅")
